### ISSUE TITLE
test_hyperbolic__fv_discretization__yaspgrid_godunov_euler is broken

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-gdt#102]
Maybe this is related to https://github.com/dune-community/dune-xt-functions/issues/18 ?

https://pastebin.ca/3888254 (Line 51)

**Comment by renemilk** [comment]
Nope. Checked again after that xt-functions/xt-common issue was fixed. I've disabled it in master now and started a branch to fix this. If @tobiasleibner could have a look at sometime that would be appreciated: https://github.com/dune-community/dune-gdt/pull/103

**Comment by tobiasleibner** [comment]
I fixed one issue and worked around another one. The test is passing now, so I reenabled it. Need to fix the second issue properly though, so leaving this open.

**Comment by renemilk** [comment]
Thanks for looking into this. I've put the commits on the PR branch and force pushed master though, since I currently cannot adjust travis for the re-enabled tests. Sorry for forgetting to mention the reason behind the PR thing.

**Comment by renemilk** [comment]
All hyperbolic tests fail with eigenvalue decomp eexceptions now. I've disabled them in master and re-pushed the WIP branch for the PR
