### ISSUE TITLE
LPsolve + Alberta broken (at least with clang)

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-gdt#104]
See https://travis-ci.org/dune-community/dune-gdt/jobs/302375470#L1717
 I've worked aroung this in https://github.com/dune-community/dune-gdt/commit/3e74f7c1845b5613dae0c063515a1d5c16eb6862

This is ofc less than optimal and should be properly addressed, somehow.

**Comment by tobiasleibner** [comment]
I fixed this by adding an lpsolve wrapper to dune-xt-common, similar to what we did with lapacke.
