### ISSUE TITLE
Check all 'associates_data_with' imps

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-gdt#105]
At least the RT one is incorrect.

**Comment by ftalbrecht** [comment]
We should postpone this until we have the new spaces, though. Those export the local finite element which knows about the `DoF <-> codim entity` relation.

**Comment by renemilk** [comment]
Yeah. The new spaces are also why I didn't do that directly PR #101

**Comment by renemilk** [comment]
Actually, for our case this is always true for ```codim == 0```, no matter the space.
