### ISSUE TITLE
[test.spaces.cg] Reenable ALU Simplex Grids

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-gdt#118]
Disabled in https://github.com/dune-community/dune-gdt/pull/114/commits/7d6f51e8fabcad852d51cc04d4121a795f09683f due to failures like https://travis-ci.org/dune-community/dune-gdt/jobs/379117170.

**Comment by renemilk** [comment]
See also https://github.com/dune-community/dune-gdt/commit/1792d219a29cc9cda9eb6c4e727194f5cf5f5ae3
which disables the linear CG tests for alugrids. Nans and infs and solver exceptions aplenty.

**Comment by tobiasleibner** [comment]
Seems to be fixed.
