### ISSUE TITLE
add a means to compare spaces for equality

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#123]
This will most likely require a means to compare grid views for equality...

**Comment by renemilk** [comment]
Out of of curiosity, when would you need that?

**Comment by ftalbrecht** [comment]
As discussed offline: in the new`OperatorInterface`. All operators hold their `source_space()` and `range_space()`, and we would like to check in some methods, e.g. `apply(source, range)` wether `source.space() == this->source_space()` (same for range).

**Comment by tobiasleibner** [comment]
Moved to gitlab.
