### ISSUE TITLE
Properly fix python tests

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-gdt#131]
The test_python compilation is broken for some time already, it was just hidden by our tests which reported success though they were failing (see e.g. https://travis-ci.org/dune-community/dune-gdt/jobs/416053350). The problem is that the python bindings in the dune-xt-modules are not added as dependencies for test_python because `bindings` is not defined as cmake target. I worked around that error in https://github.com/dune-community/dune-gdt/pull/128/commits/f9fc174f8606a49e4da1f6e9e13c63318039129f but someone who is more familiar with our python setup should fix it properly.

**Comment by renemilk** [comment]
I probably got this covered in my personal branch. Will check.

**Comment by renemilk** [comment]
I think this should be good now, yes?

**Comment by tobiasleibner** [comment]
Yes, probably.
