### ISSUE TITLE
add interfaces for (local) DoF vectors and (local) discrete functions

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#136]
Otherwise we will run into trouble in the long run. I stumbled upon this when implementing automatic jacobians by finite differences in https://github.com/ftalbrecht/dune-gdt/blob/refactor-space-interface/dune/gdt/local/assembler/operator-fd-jacobian-assemblers.hh

**Comment by tobiasleibner** [comment]
Moved to gitlab.
