### ISSUE TITLE
Clean up old master branches

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-gdt#150]
When merging the ``new-master``, I created a branch ``oldmaster`` as a copy of the ``master`` branch at that point. @renefritze created a branch ``old_master`` some time before. The only difference between these two branches is that in ``old_master`` the new clang-format spec is applied. 
Do we need both of these branches, i.e., do we need the old master with the old clang-format? If yes, we should probably rename these branches to something like ``old_master_clangformat6.0`` and ``old_master_clangformat3.9``.

**Comment by renefritze** [comment]
I don't think we need the state before clang format.

**Comment by tobiasleibner** [comment]
@ftalbrecht, do you agree? In that case, I will just delete the ``oldmaster`` branch.

**Comment by ftalbrecht** [comment]
I agree, sorry for the delay.
