### ISSUE TITLE
allow for larger stencil in finite difference jacobians of element operators

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#154]
While being only element operators, they might depend on values of the source from neighbors (by internally doing a walk over the intersections). Thus, when appending those to the matrix jacobian we should also specify the stencil used in the FD approximation...

This is required for higher order implicit DG to work for hyperbolic poblems...

**Comment by ftalbrecht** [comment]
related to #174, should be implemented alongside

**Comment by tobiasleibner** [comment]
Moved to gitlab.
