### ISSUE TITLE
improve ContinuousMapper

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#156]
I think that we will have a problem in the future with the continuous mapper, since for higher order scalar spces we will also have multiple basis functions per subentity (as in the vector-valued case), but those need to be handled differently than the vector valued case (they need to be twisted if looking from the other element). In addition, we might have different numbers of bases per type of subentity.

So we should probably revert the ContinuousMapper to its previous state to allow for higher orders, call it ScalarContinuousMapper and add a VectorMapper which takes any scalar mapper per component and makes a corresponding vector mapper. The COntinuousMapper should then hold on of those, depending on the dimension...

**Comment by renefritze** [comment]
Sounds good :+1:

**Comment by tobiasleibner** [comment]
Moved to gitlab.
