### ISSUE TITLE
let operators/functionals/bilinear forms handle non-affine geometries

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#184]
Currently, the integrands "handle" non-affine geometries by warning when bound to an element with non-affine geometries. This is not the best way to do, I think.
The local operators/functionals/bilinear forms are the ones performing the integration and are responsible for computing the right quadrature order (this is already the case by asking the integrand and the user via `over_integrate`).
This is also the right place to handle non-affine geometries and increase quadrature order if required.
Does anyone know of a means to obtain the polynomial order of the geometry transformation? I did not find one...

As a first step I will move the warnings from the integrands to the operators/functionals/bilinear forms...

**Comment by tobiasleibner** [comment]
I think there is no way to get the order. If there was, it should be in the ``Geometry`` interface, but the interface only provides the ``affine()`` method. We could set a high default ``over_integrate`` (about 50?) if the user-provided ``over_integrate`` is ``0`` and the geometry is not affine and issue a warning that the quadrature order might be too high and that the user should provide the correct order.

**Comment by ftalbrecht** [comment]
On 10.07.20 11:44, Tobias Leibner wrote:
> I think there is no way to get the order. If there was, it should be in the ``Geometry`` interface, but the interface only provides the ``affine()`` method. We could set a high default ``over_integrate`` (about 50?) if the user-provided ``over_integrate`` is ``0`` and the geometry is not affine and issue a warning that the quadrature order might be too high and that the user should provide the correct order.
> 

We could also take a look at which grids support non-affine elements and
what kind of transformations these are to obtain a lower suitable
`over_integrate`. Until then I would proceed as proposed, yes.

**Comment by tobiasleibner** [comment]
Moved to gitlab.
