### ISSUE TITLE
renaming/cleanup before the next release

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#188]
- [ ] drop `Local` from integrands, possibly other stuff in `local/`
- [ ] drop `Localizable` from `LocalizableBilinearFormBase`, possibly other stuff (localizable means we can walk over the grid, kind of the base assumption in dune)
- [x] `LocalizableBilinearFormBase` -> `BilinearForm`

**Comment by ftalbrecht** [comment]
* `MatrixOperator` should not be a grid walker, rather create one in assemble and otherwise be merged with/derive from the local assembler

**Comment by ftalbrecht** [comment]
* [ ] rename `LocalizableOperator` -> `Operator`
* [ ] update/add bilinear form like localizable operator, possibly derive from operatorinterface

**Comment by ftalbrecht** [comment]
in `dune-xt`:

* [ ] in `WithLogger`: drop `logging_prefix` argument, use `logging_id` as prefix, use id for logging propagation (`this.logging_id + '*' + other.logging_id`), use own class name isntead of id elsewhere (`LOG_(debug) << "GridFunctionInterface.name(" << ...`)

**Comment by ftalbrecht** [comment]
* [ ] use `GridFunctionInterface` instead of `GridFunction` again in integrands and check lifetime of temporaries

**Comment by ftalbrecht** [comment]
* [ ] add `print` to `Functions` and `LA` namespace

**Comment by ftalbrecht** [comment]
* [ ] check if we need `L2VolumeVectorFunctional`

**Comment by ftalbrecht** [comment]
- [ ] rename `with_source` to `with` (or `with_`)

**Comment by ftalbrecht** [comment]
- [ ] derive local operators from local functionals #174

**Comment by tobiasleibner** [comment]
Moved to gitlab.
