### ISSUE TITLE
pybind11s def_property does not work as expected

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#191]
We have a problem with the `vector` property of the discrete function, the same applies to the `vector` property of functionals and the `matrix` property of operators. Consider:

```python
from dune.xt.grid import Dim, make_cube_grid
from dune.xt.la import IstlVector

from dune.gdt import ContinuousLagrangeSpace, DiscreteFunction

d = 1
grid = make_cube_grid(Dim(d), lower_left=[0], upper_right=[1], num_elements=[2])

V_h = ContinuousLagrangeSpace(grid, order=1)

a = DiscreteFunction(V_h)
b_vec = IstlVector(V_h.num_DoFs)
```

The DoF vector of `a` has a `vector` property which should give us (read and write) access to the discrete functions DoF vector. Indeed, this code

```python
a_vec = a.dofs.vector
print(a_vec)
print(type(a_vec))

a_vec[1] = 1
print(a.dofs.vector)
```

gives the desired output:

```
IstlVector([0 0 0])
<class 'dune.xt.la._la.IstlVector'>
IstlVector([0 1 0])
```

We may thus deduce that `a_vec` references the correct object.

We may also create another vector of appropriate length,

```python
b_vec[2] = 2
print(b_vec)
print(type(b_vec))
```

which gives

```
IstlVector([0 0 2])
<class 'dune.xt.la._la.IstlVector'>
```

Using these we can

```python
print(a_vec)
a_vec -= b_vec
print(a_vec)
print(a.dofs.vector)
```

which gives

```
IstlVector([0 1 0])
IstlVector([0 1 -2])
IstlVector([0 1 -2])
```

so `__isub__` should be working as expected (replacing ` -= b_vec` by `.__isub__(b_vec)` indeed gives the same results).

So, all in all, the vector itself behaves as expected. **However**, calling

```python
a.dofs.vector -= b_vec
```

fails with

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-7e281c6ba1ab> in <module>
----> 1 a.dofs.vector -= b_vec

TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: dune.gdt._discretefunction_dof_vector.DofVector1dSimplexOnedgridIstlVector) -> dune.xt.la._la.IstlVector

Invoked with: <dune.gdt._discretefunction_dof_vector.DofVector1dSimplexOnedgridIstlVector object at 0x7ff5cebaf0f0>, IstlVector([0 1 -4])
```

as does an assignment like

```python
a.dofs.vector = b_vec
```

which gives

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-640e81a3e625> in <module>
----> 1 a.dofs.vector = b_vec

TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (arg0: dune.gdt._discretefunction_dof_vector.DofVector1dSimplexOnedgridIstlVector) -> dune.xt.la._la.IstlVector

Invoked with: <dune.gdt._discretefunction_dof_vector.DofVector1dSimplexOnedgridIstlVector object at 0x7ff5cebaf0f0>, IstlVector([0 0 2])
```

The C++ code responsible for exposing the `vector` attribute of the DoF vector is

```cpp
c.def_property("vector", (const V& (type::*)() const) & type::vector, (V & (type::*)()) & type::vector);
```

where the 2nd argument to `def_property` is the getter method and the 3rd argument is the setter method.
Instead of these function pointers one could also provide C++ lambdas to facilitate debugging (we could inject some intermediate code there), but I never managed to get the return value policies right then (`a_vec` ends up as a copy then, not a reference to `a.dofs.vector`).

Any ideas or hints are appreciated, @sdrave @renefritze @TiKeil

**Comment by renefritze** [comment]
*I skipped to error part*
This is the `vector` function that's being exposed, right? 
https://github.com/dune-community/dune-gdt/blob/master/dune/gdt/discretefunction/dof-vector.hh#L86
Then AFAICS that cannot work as the `def_property` implementation wants to use this a classical getter/setter method, i.e. input the "new" object as first arg for the setter func (after resolving `this`).
Maybe try that with a lambda somewhat like this?
```
c.def_property("vector", (const V& (type::*)() const) & type::vector, [](type& self, const type& vec){self.vector = vec} );
```

**Comment by ftalbrecht** [comment]
> This is the `vector` function that's being exposed, right?
> https://github.com/dune-community/dune-gdt/blob/master/dune/gdt/discretefunction/dof-vector.hh#L86

yes

> Then AFAICS that cannot work as the `def_property` implementation wants to use this a classical getter/setter method, i.e. input the "new" object as first arg for the setter func (after resolving `this`).

K, that makes sense.

> Maybe try that with a lambda somewhat like this?
> 
> ```
> c.def_property("vector", (const V& (type::*)() const) & type::vector, [](type& self, const type& vec){self.vector = vec} );
> ```

Will try that, never got the return type to work, though. But in case the lambda does not work, I will just extend the bindings class to be a small trampoline with a different setter method. Thx!

**Comment by ftalbrecht** [comment]
So my trouble with the wrong return type and the wrong ownership handling only ever was with the getter, not the setter. Letting the getter remain the member function pointer and the setter a lambda like above, everything works as expected!

Thx a lot

**Comment by ftalbrecht** [comment]
However, this raises another question. If calling
```python
a.dofs.vector -= b_vec
```
involves the setter method, then this will be an additional copy of the vector, which is not required.
Looking at [the docs](https://docs.python.org/3.4/library/operator.html#operator.__isub__), it looks indeed like the above is equivalent to
```python
a = isub(a, b)
```
which would mean an unnecessary copy.
