### ISSUE TITLE
Bug in SharedDOFGatherScatter?

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-gdt#192]
In ``dune/gdt/spaces/parallel/datahandles.hh`` we have the following code

```c++
573   template <typename MessageBuffer, typename Entity, typename LocalView>
574   bool scatter(MessageBuffer& buff, std::size_t /*n*/, const Entity& /*e*/, LocalView& local_view) const
575   {
576     bool remote_entity_has_dofs;
577     buff.read(remote_entity_has_dofs);
578 
579     for (std::size_t i = 0; i < local_view.size(); ++i) {
580       local_view[i] |= remote_entity_has_dofs;
581     }
582     return true;
583   }
584 };
```

I am not sure what line 580 does. ``local_view[i]`` is of type ``uint_fast8_t``, so basically an integer. When applying the bitwise or, the boolean ``remote_entity_has_dofs`` is converted to either ``0`` or ``1``. In case of ``0``, nothing is changed. In case of ``1``, the last bit of ``local_view[i]`` is set (if it is not already set). So if, e.g., ``local_view[i]`` is ``1``, it will still be ``1`` after line 580. If it is ``2``  before, it becomes ``3``. Maybe this should only set ``local_view[i]`` to either ``1`` or ``0``? In that case, can ``local_view`` simply contain ``bool``s?

Only stumbled upon this because the Intel compiler gave a narrowing warning at this line. Everything seems to work fine, so no need to hurry fixing this.

**Comment by renefritze** [comment]
At the time of writing the element type for local_view could not be bool, since std::vector has a specialization for bool that behaves differently in some cases. Then uint_fast8_t was guaranteed smallest  type to simulate bool with an integer type, the bit op is used so the lhs isn't converted to bool all the time.

**Comment by tobiasleibner** [comment]
Okay, I added a comment to the source code.
