### ISSUE TITLE
[spaces.dg.pdelab] do not seem to work

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#25]
Running `test/operators_projections_l2_dg_pdelab.cc` yields lots of errors for me, indicating together with #10 that the wrapper for DG spaces is totally broken for dune-pdelab.

**Comment by renemilk** [comment]
We're good here?

**Comment by tobiasleibner** [comment]
I think we can close this, the bug should be fixed. The performance may be bad, but that is #46.
