### ISSUE TITLE
move to dune-community

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#37]
This will change project and repository URLs.

**Comment by renemilk** [comment]
I'm guessing the same goes for dune-{hdd,grid-multiscale,gdt-demos,hdd-demos}?

**Comment by ftalbrecht** [comment]
More or less, yes. I still have to figure out some permission settings, though... And I would rename the super modules from -demos to -tests, as we do not really have demos any more.

**Comment by renemilk** [comment]
Well, justike there never were any actual demos in those super modules, there aren't any tests in them now. So I'd say names are still kinda misleading.

**Comment by ftalbrecht** [comment]
Well, we pretty much mostly use those super module for the automated testing. So I think `-tests` or `-testing` is appropriate, since they should have some name and we do not have anything better.

**Comment by renemilk** [comment]
You know what's a pretty good name imo? "-super" because it's a super module.

**Comment by ftalbrecht** [comment]
done by now
