### ISSUE TITLE
do not duplicate pdelabs GridFunctionSpace

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#45]
I just talked to Steffen and he argued that copying the GridFunctionSpace for every thread might get very costly. Instead we should consider to just duplicate the local function space (since the entity binding is done here) instead. I am not sure if we really suffer from this, so this is mainly a reminder to investigate.

**Comment by ftalbrecht** [comment]
To clarify the current situation:

* we do not copy the spaces, but create one for each thread. So if the problem lies in the copying, then we do not care about it
* if we only have one space and duplicate the local function space internally for each thread then we need to dereference the `PerThreadValue` vector (and thus get the current thread id) several times on each entity. As far as I remember this was a serious performance drain.

So all in all: I will leave this open for a bit but I think we will not change anything for the time being...

**Comment by ftalbrecht** [comment]
Could you clarify a bit, which of the two exactly is problematic (copying a space vs. having many spaces), @smuething?

**Comment by renemilk** [comment]
Closing in advance of external space backend removal.
