### ISSUE TITLE
make use of pdelabs EntityIndexCache in our mapper

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#46]
I just talked to Steffen and he argued that our hacks to obtain the correct mapping from the pdelab clasess could be streamlined by using the `EntityIndexCache` from `dune/pdelab/gridfunctionspace/entityindexcache.hh`. It is also more general and faster.

**Comment by tobiasleibner** [comment]
We do not depend on pdelab anymore.
