### ISSUE TITLE
cache evaluations of basefunctions

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#47]
I just talked to Steffen and he argued that the evaluation of shapefunctions for higher order DG is quite expensive. I think this is also what we see in our tests for higher order DG. He suggested to implemented a caching of the evaluations using a hashed map (`FieldVector`s are hashable by now, this would happen in our basefunctionset). We should create a simple test case to measure possible performance impact for lower order spaces and possible performance gains for higher order spaces.

**Comment by tobiasleibner** [comment]
Moved to gitlab.
