### ISSUE TITLE
[projections.lagrange] merge with oswald interpolation operator

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#55]
The way the Lagrange projection is currently implemented may be problematic. The same holds for the Lagrange prolongation, but that will not be an issue after #54.
The problem arises when applying the Lagrange projection to a localizable function that is discontinuous across the faces of the grid: we carry out the projection locally by assigning the values of the local DoF vector on each entity. Since there are Lagrange points that are shared by more than entity, the value of the projected function is not unique in that point and only depends on the ordering of the elements in the grid.

I propose to merge the oswald interpolation operator into the Lagrange projection. That operator basically takes the average value at each Lagrange point, which is probably what we want (and at least deterministic). In addition we might want to statically drop to the old behaviour if the source is contained in a continuous space for performance reasons, since the current approach is correct in those cases.

**Comment by tobiasleibner** [comment]
Is this still relevant? There were a lot of changes since 2015.

**Comment by ftalbrecht** [comment]
not sure if we want this anyway
