### ISSUE TITLE
[linearelliptic.discretizers.cg] add detection and handling of pure Neumann cases

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#57]
We already have the `DirichletDetector` functor in dune-stuff. We only need to apply it and pass the information to the discretization container (so it can fix a DoF and subtract the mean afterwards).

**Comment by tobiasleibner** [comment]
Does this issue still apply?

**Comment by ftalbrecht** [comment]
we have no cg tests currently, but this can be easily added if required
