### ISSUE TITLE
improve threaded assembly

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#59]
While refactoring I stumbled across several places where we seem to treat the threaded assembly case differently. I think in the long run we need a clear concept of what is good and what is bad.

If I remember correctly, we do not want to dereference `PerThreadValue` on each grid entity (since it then has to determine which element to pick according to the current thread, and that may be slow). That was one of the reasons why we duplicate the spaces in the `SystemAssembler` (before we had a `PerThreadValue` vector of space backends in each space and dereference that on each call associated with an entity). Nevertheless, we have several wrappers in `dune/gdt/assembler/wrapper.hh` (the purpose of which is to wrap, e.g., a local assembler into a usable functor) that are constructed with the `PerThreadValue` of spaces and locally dereference that on each entity. That, however, is just as bad as having all the magic inside the spaces (if I am not mistaken about the current situation).

If that is true, we would have to duplicate the wrappers and functors within the `add` methods of the `SystemAssembler`. Most wrappers deal with local operators (and thus with local evaluations) where everything is const and should be thread safe (TM). If we drop the current tmp storage, however, (as decided in #49), those objects hold mutable tmp storage and need to be duplicated as well...

All in all I think we have a nice intertwined situation and should come up with a general concept of the good, the bad and the ugly in the context of threaded assembly. In particular at what point we want to duplicate which kind of objects, etc ...

**Comment by ftalbrecht** [comment]
After pondering on the issue a bit more I think the only viable solution is to have a copy of each functor added to the grid walker/assembler for each thread, by means of `PerThreadValue` containers of the functors in [`walker.hh`](https://github.com/wwu-numerik/dune-stuff/blob/master/dune/stuff/grid/walker.hh#L314)

**Comment by tobiasleibner** [comment]
This is done, we now copy each functor to each thread.
