### ISSUE TITLE
[tests.linearelliptic] add more test cases

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#61]
I found another one in the diploma thesis of S. Kaulmann (Section 6.1.1): taking `\lambda = \kappa = 1` and `f = -q (q - 1) x^{q - 2}` on the unit cube in 2d with Dirichlet boundary values `g_D = x^q` everywhere (for any `q \in \N`) yields the exact solution `p(x) = x^q`.

**Comment by ftalbrecht** [comment]
Another two are in ER2007, page 858 (we already use the 2d one):
* 1d: exact solution `cos(8 pi x)`
* 3d: exact solution `cos(8 pi x) cos(8 pi y) cos(8 pi z)`

**Comment by renemilk** [comment]
You've add the ER2007 case since posting. I do think the polynomial one would still be nice though.

**Comment by ftalbrecht** [comment]
Agreed, will do. Perhaps after #97 is done, recording the results should be nicer then.

**Comment by tobiasleibner** [comment]
Moved to gitlab.
