### ISSUE TITLE
Finite Volume methods

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#63]
After a small discussion we decided to implement the following (this might be of interest to @sdrave and @tobiasleibner):
# local operators
## interfaces

Some new CRTP interfaces in `localoperator/interfaces.hh`:
- `LocalCouplingOperatorInterface`:

``` c++
template< class Traits >
class LocalCouplingOperatorInterface
{
public:
  template< class SourceType, class IntersectionType, class S, class V >
  void apply(const SourceType& source,
             const IntersectionType& intersection, 
             const LocalDiscreteFunction<S, V>& local_range_entity,
             const LocalDiscreteFunction<S, V>& local_range_neighbor);
};
```
- `LocalBoundaryOperatorInterface`:

``` c++
template< class Traits >
class LocalBoundaryOperatorInterface
{
public:
  template< class SourceType, class IntersectionType, class S, class V >
  void apply(const SourceType& source,
             const IntersectionType& intersection, 
             const LocalDiscreteFunction<S, V>& local_range_entity);
};
```
## implementations

Generic Finite Volume operators (without reconstruction for the moment) based on these interfaces in `localoperators/fv.hh`:
- `LocalCouplingFVOperator : public LocalCouplingOperatorInterface`
- `LocalBoundaryFVOperator : public LocalBoundaryOperatorInterface`

These operators make use of the following numerical fluxes.
# numerical fluxes
## interface

New CRTP interfaces in `localfluxes/interfaces.hh`:

``` c++
template< class Traits >
class NumericalCouplingFluxInterface
{
public:
  LocalfunctionTupleType local_functions(const EntityType& entity);

  template< class E, class D, size_t d, class R, size_t r, size_t rC, class IntersectionType >
  ResultType evaluate(const LocalfunctionTupleType& local_functions_tuple,
                      const Stuff::LocalfunctionInterface< E, D, d, R, r, rC >& local_source_entity,
                      const Stuff::LocalfunctionInterface< E, D, d, R, r, rC >& local_source_neighbor,
                      const IntersectionType& intersection,
                      const FieldVector< D, d - 1 > x_intersection);
};
```

``` c++
template< class Traits >
class NumericalBoundaryFluxInterface
{
public:
  LocalfunctionTupleType local_functions(const EntityType& entity);

  template< class E, class D, size_t d, class R, size_t r, size_t rC, class IntersectionType >
  ResultType evaluate(const LocalfunctionTupleType& local_functions_tuple,
                      const Stuff::LocalfunctionInterface< E, D, d, R, r, rC >& local_source,
                      const IntersectionType& intersection,
                      const FieldVector< D, d - 1 > x_intersection);
};
```
## implementations

In `localfluxes/{laxfriedrichs,godunov}.hh`

These implementations are based on the following analytical fluxes.
# analytical fluxes
## interface

New virtual interface in `localfluxes/interfaces.hh`, modeling an analytical flux

```
F: u(x) \times x \times t -> \mathbb{R}
```

or

```
F: u(x) \times \nabla u(x) \times x \times t -> \mathbb{R}
```

The meaning of the template arguments is as follows: `R`, `r` and `rC` model `u(x)`, `E` models the entity that is required to interprete the local point x and `D` and `d` model `x`.

``` c++
template< class E, class D, size_t d, class R, size_t r, size_t rC = 1, bool gradient = false>
class AnalyticalFluxInterface
{
public:
  typedef ... RangeType; // of u, FieldVector of FieldMatrix depending on dimensions
  double evaluate(const RangeType& u,
                  const E& entity,
                  const FieldVector< D, d >& x_local,
                  const double t_ = 0) = 0;
};

template< class E, class D, size_t d, class R, size_t r, size_t rC >
class AnalyticalFluxInterface< E, D, d, R, r, rC, true >
{
public:
  typedef ... RangeType; // of u, FieldVector of FieldMatrix depending on dimensions
  typedef ... RangeType; // of gradient of u, FieldMatrix depending on dimensions
  double evaluate(const RangeType& u,
                  const JacobianRangeType& grad_u,
                  const E& entity,
                  const FieldVector< D, d >& x_local,
                  const double t_ = 0) = 0;
};
```
## implementations

For the moment in `localfluxes/analytical.hh`

**Comment by ftalbrecht** [comment]
So, we have an implementation by now, thanks to @tobiasleibner. It is not finished, however. Remaining issues:
* the `RhsEvaluationFluxInterface` seems to be obsolete, use `AnalyticalFluxInterface<..., false>` instead
* the `InstationaryDefaultDiscretization` is not an instationary default discretization, but a finite volume discretization. Either this has to be generic (just gets operators and timesteppers) or this has to be renamed.
* the product spaces are not yet finished, see #76

**Comment by tobiasleibner** [comment]
Outdated, if we want to improve the FV methods we should start a new issue.
