### ISSUE TITLE
[travis] add linting

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#69]
See @renemilk's comment in pr #67.

**Comment by renemilk** [comment]
Something akin to
```bash
gem install travis
cd ${GIT_ROOT}
travis lint
```

**Comment by renemilk** [comment]
Since I'm generating ```.travis.yml``` linting of the generated output could easily be done automatically. 

Any idea what the 'offline checks' were meant to be?

**Comment by ftalbrecht** [comment]
No, I just recall the linting of the `travis.yml`...
