### ISSUE TITLE
add LagrangeSpaceInterface

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#73]
As a follow up to #14:

This interface should
- derive from `SpaceInterface`,
- require `lagrange_points`,
- provide a default implementation of lagrange points that can be used by derived classes (copy @tobiasleibner recent implementation here).

Accordingly,
- `CgSpaceInterface` and `DgSpaceInterface` should derive from `LagrangeSpaceInterface` (and their names be updated, i.e. `CgLagrangeSpaceInterface`,
- the names and implementations of all CG and DG spaces and wrappers should be updated,
- the new interfaces should be used everywhere (in particular projections, prolongations, ...)

**Comment by tobiasleibner** [comment]
We have something like this now, closing this.
