### ISSUE TITLE
Problems with dune-alugrid 

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-gdt#79]
In the transition from the external module alugrid to dune-dalugrid I've ran into mulitple weird assertions and exceptions in our tests. After more than a day I've only managed to narrow the issue down to be confined to 3d + simplex + confirming. I've removed this from our grid type selection for now. 

This needs to be reverted and re-examined ofc. Asap.

**Comment by tobiasleibner** [comment]
Probably not relevant anymore?
