### ISSUE TITLE
[assembler.apply_on]

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#8]
According to some thoughts we had the `ApplyOn::BoundaryIntersections` should return true if

```
!intersection.bounday() && !intersection.neighbor()
```

in the parallel case. Investigate! :)

**Comment by ftalbrecht** [comment]
Is this still an issue? Maybe @renemilk can judge...

**Comment by tobiasleibner** [comment]
Is this still relevant?

**Comment by ftalbrecht** [comment]
I dont think so, no
