### ISSUE TITLE
Deploy pre-commit clang-format hook using dunecontrol

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#81]

**Comment by renemilk** [comment]
dunecontrol has no actual mechanism to deploy hooks other than dune-common's whitespace hook. What it does have is a facility to run _arbitray_ scripts which we'll use to deploy scripts.
Each module that wants to use this will add https://github.com/dune-community/vcsetup as a submodule at ```.vcsetup```, the rest is magic then.
