### ISSUE TITLE
make SystemAssembler movable?

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#89]
In its current state, the `SystemAssembler` cannot be moved or copied (although I always assumed it could):

* we use type-erasure to stack the incoming functors via wrappers
* these wrappers hold a reference to the spaces
* upon move (and copy) of the `SystemAssembler`, these objects hold invalid references

In general, it would be nice to hava a movable `SystemAssembler`, since this is the base class for many operators. A possible solution would be

* to introduce a second kind of functor (in addition to the ones from the `Walker` base class), with an `apply_local` method which accepts the spaces. This is problematic, since
  * it is not clear how many spaces to provide upon call: 1, 2 or 4. Would always providing 4 be enough, can we think of future situations where we require more? (Could be solved as below, not really an issue)
  * we would need to copy the walk from the base `Walker` to call this method locally. (really an issue: we do not want to duplicate (this) code! We might get away with a second layer of wrappers which wrap these functors given the current spaces into the functors of the `Walker`...)
* to introduce new kinds of functors (...) for the 1-space, 2-space, 4-space cases which we hold in a separate stacks. These provide some kind of `update_spaces` method which replaces the references of the spaces.
  * this could be acchieved by using `unique_ptr<XT::Common::ConstStorageProvider<Space>>`, and replacing those.
  * on move, we would first need to refresh the spaces before move of the base `Walker` takes place, which could perhaps be realized by a base class which acts before the `Walker` base.

All in all: lot's of fun! :)

**Comment by tobiasleibner** [comment]
SystemAssembler is gone, the matrix-based operator seems to be movable.
