### ISSUE TITLE
problems reading cmake cache

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#93]
More info will follow

**Comment by ftalbrecht** [comment]
To reproduce, execute the following command and follow the instructions. `qtcreator`, `gdb`, and so on should be available, local user is `sudo` capable without password (although installing something requires you to run `sudo apt-get update` first):
```bash
sudo docker run -t -i --hostname docker -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/localtime:/etc/localtime:ro dunecommunity/dailywork:dune-gdt-issue-93 /bin/bash
```

**Comment by renemilk** [comment]
SIdenote: ```$HOME``` is set incorrectly to ```/home```, and not ```/home/user``` in that dockerfile. Awesome way to replicate the issue within 1 minute though. :+1:

**Comment by renemilk** [comment]
Fixed in https://github.com/dune-community/dune-xt-common/commit/90160f2c375021740d398c72ddd22d2c1b195409
