### ISSUE TITLE
extend bindings

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#95]
Python bindings are currently limited to only a few grid/space/la combinations, as compiling them takes ages. We should at some point enable the rest and/or move some compilation effort into a libdunegdt...

**Comment by renemilk** [comment]
I've currently fixed the used GridType for the python bindings per CMake Cache option. This, plus complexity reduction via fem+pdelab removal has brought down compile time by 15x (44m to 3m) for me. Imo we should have a very, very good reason to precompile more variations again at some point in the future. Additionally that process needs to be more flexible than the current Macro nesting, i.e. explicit python templating that one can configure at configure time with a user defined python script. 

As such IMO we can close this.

**Comment by ftalbrecht** [comment]
As I said: I would love to have multiple grids in the future but I am happy with the current state. Thx a lot!

**Comment by tobiasleibner** [comment]
Moved to gitlab.
