### ISSUE TITLE
hyperbolic tests fail to build

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-gdt#96]
During porting our docker setup to the dailywork_debian repositories I ran into build failures in the hyperbolic subtree. I'm disablinig them for now so I can continue on with the setup checks. Could you please have a look at that @tobiasleibner and revert the disabling commit?

**Comment by ftalbrecht** [comment]
s.a. https://travis-ci.org/dune-community/dune-xt-grid/builds/233203142

**Comment by tobiasleibner** [comment]
Yep, I will look into it.

**Comment by tobiasleibner** [comment]
Fixed by #100.
