### ISSUE TITLE
Rewrite test expectation handling

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-gdt#97]
The current system where explicit instantiations of expectation classes need to be manually filled, compiled, re-edited, compiled and so on desperately needs replacing (IMO).
What I want to do is rewrite the whole thing to enable this workflow:
- Add a new test class
- Compile
- First run outputs CSV with results
- add CSV to git
- Rerun now checks the against the CSV

I'll probably start working on this late June, comments welcome.

**Comment by renemilk** [comment]
@ftalbrecht  noted that I should consider keeing test conifguration and expectation in the same input/output file. So prolly a ```DXTC::Configuration``` object.

**Comment by ftalbrecht** [comment]
Without the automatic csv part, I am doing something similar in https://github.com/dune-community/dune-gdt/blob/master/dune/gdt/test/stationary-heat-equation/stationary_heat_equation__ESV2007__table_1.cc and the related `.mini`. Setup and expectations are in the mini, the test is set up according to the mini, the actual reseults are compared to the expected.

**Comment by tobiasleibner** [comment]
Moved to gitlab.
