### ISSUE TITLE
dune-functions based DG spaces broken

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt#98]
While the tests of the actual space work, assembling does not work.

**Comment by ftalbrecht** [comment]
As in: segfaults (`free(): invalid next size (fast)`).

**Comment by renemilk** [comment]
So the space tests should also get to assemble something until you figure out exactly what wasn't covered by the current tests, yes?

**Comment by ftalbrecht** [comment]
This might be an option, to catch this earlier. But then we have to depend on the assembly code to be correct in order to test the spaces, but it might be worthwile, nevertheless.

**Comment by renemilk** [comment]
Well, the assembly code is tested too, right?

**Comment by renemilk** [comment]
These spaces do not exist any more.
